<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- 核心配置必须正确 -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<!-- 这个必须指定！ -->
                <RuntimeIdentifier>win-x64</RuntimeIdentifier>
		 <!-- 包含所有内容 -->
                <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
                <!-- 启用 ReadyToRun 编译（提高启动速度） -->
                <PublishReadyToRun>true</PublishReadyToRun>


		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<StartupObject></StartupObject>
		<ApplicationIcon>Halcon 查询.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resource\HalconSearch.db" />
		<None Remove="Resource\Halcon算子手册-1-672.pdf" />
		<None Remove="Resource\Halcon算子手册目录_QS整理.csv" />
		<None Remove="Resource\书.png" />
		<None Remove="Resource\放大镜.png" />
		<None Remove="Resource\目录.png" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Halcon 查询.ico" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resource\HalconSearch.db" />
		<EmbeddedResource Include="Resource\Halcon算子手册-1-672.pdf" />
		<EmbeddedResource Include="Resource\Halcon算子手册目录_QS整理.csv" />
		<EmbeddedResource Include="Resource\书.png" />
		<EmbeddedResource Include="Resource\放大镜.png" />
		<EmbeddedResource Include="Resource\目录.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3650.58" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
		<PackageReference Include="PDFiumCore" Version="147.0.7699" />
	</ItemGroup>

</Project>
